### ISSUE TITLE
[Bug] on [server-version] - short description

### ISSUE THREAD

**Issue by AWobbuffet** [eingruenesbeb/Yolo#6] opened 2023-04-11 21:41 UTC
**/revive**
Whenever you kill someone and revive them using /revive, if they die again they don't get banned anymore and can rejoin as much as they'd like to even after death.

**To Reproduce**
1. Install the plugin on a server
2. Kill someone
3. Revive them
4. Kill them again
5. See error

**They stay banned**
When they die a second time I want them to stay banned.

(I can't get screenshots)

**Environment:**
 - OS: Microsoft
 - Server-version paper 1.19.2
 - None

**Comment by eingruenesbeb** [comment] 2023-04-11 22:19
Hey,
Thanks for reporting the issue. I'll look into it asap. 

If you don't mind, could you provide me with the plugin's playerdata from your server as well as the UUID or name of an affected player? You should find the file (relative to your server's root directory) in `./plugins/yolo/data/yolo_playerdata.json`.

**Comment by eingruenesbeb** [comment] 2023-04-12 16:57
Hey, I've yet to reproduce the bug, as you've described. But there's something very peculiar here:
The plugin will ban everyone (revived or not), who dies, that does not have the `yolo.exempt` permission and if the plugin's functionality is not to disabled via the config.
Therefore, I'd like to ask of you, if you could share your current plugin configuration and maybe checking the permissions.

**However:** I have found a bug, which might be tangentially related (and is very silly). If you'd like, you could try the currently indev version in the attachments and report back, if the issue is solved.
[Yolo-0.6.1.zip](https://github.com/eingruenesbeb/Yolo/files/11214805/Yolo-0.6.1.zip)

**Comment by eingruenesbeb** [comment] 2023-04-17 18:59
@AWobbuffet 
Hello again; I was still not able to reproduce your issue. I'll merge the fix for the other bug, I've discovered soon, thus officially closing this issue. 
The new version will include a fix for players receiving the revive effects far too early in some cases and the player data being saved regularly. I hope, this will fix this issue as well. 

**If this issue persists, feel free to reopen this issue, providing the additional information, I've asked for previously.**

**Closed as completed** 2023-04-17 19:12 UTC
Labels: bug

**Comment by AWobbuffet** [comment] 2023-04-22 04:38
I forgot to respond however yes, 0.61 did fix the issue I was having. Thank you very much!
